[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fluxdisco"
version = "1.0.0"
maintainers = [
  { name="Cassandra Durr", email="c.durr@lancaster.ac.uk" },
]
authors = [
  { name="Cassandra Durr", email="c.durr@lancaster.ac.uk" },
]
dynamic=["dependencies", "optional-dependencies"]
license={file="LICENSE"}
description = "Symbolic Regression for Stoichiometric Dynamical Systems via Monte Carlo Graph Search."
readme = "README.md"
requires-python = ">=3.14"
keywords=["equation-discovery", "physics-informed", "MCGS", "symbolic-regression", "stoichiometric-systems"]
classifiers = [
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.dynamic]
dependencies={file="requirements/requirements.txt"}
optional-dependencies={dev={file=["requirements/requirements-dev.txt"]}}

[project.urls]
"Homepage"="https://github.com/CassandraDurr/FluxDisco"
"Bug Tracker"="https://github.com/CassandraDurr/FluxDisco/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["fluxdisco", "fluxdisco.*"]
exclude = ["fluxdisco.example*", "fluxdisco.paper-results*"]

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["."]
addopts = "--strict-markers"
